<?php

namespace App\Services;

use App\Models\Client;
use App\Models\User;
use App\Models\WhatsappInstance;
use App\Services\CreditService;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

class InstanceService
{
    public function __construct(
        private readonly CreditService $creditService,
    ) {}

    /**
     * Create a new WhatsApp instance record.
     *
     * $owner can be a User (role: user or super_admin) or a Client (role: client_admin).
     * If $creditsToAssign > 0, immediately allocate from the owner's wallet.
     *
     * @throws ValidationException
     * @throws AuthorizationException
     */
    public function create(
        User|Client $owner,
        string      $name,
        int         $creditsToAssign = 0,
        ?string     $webhookUrl = null,
    ): WhatsappInstance {
        return DB::transaction(function () use ($owner, $name, $creditsToAssign, $webhookUrl) {

            // Determine owner_type and client_id
            [$ownerType, $clientId] = $this->resolveOwnerMeta($owner);

            // Validate max instances per user (not checked for super_admin or client)
            if ($ownerType === WhatsappInstance::OWNER_TYPE_USER) {
                $this->assertInstanceLimit($owner, $clientId);
            }

            // Validate credits available if assigning now
            if ($creditsToAssign > 0) {
                $balance = $ownerType === 'client'
                    ? $owner->credit_balance
                    : $owner->credit_balance;

                if ($balance < $creditsToAssign) {
                    throw ValidationException::withMessages([
                        'credits' => "Insufficient credits. Available: {$balance}, Requested: {$creditsToAssign}.",
                    ]);
                }
            }

            // Create the instance record
            $instance = WhatsappInstance::create([
                'owner_id'    => $owner->id,
                'owner_type'  => $ownerType,
                'client_id'   => $clientId,
                'name'        => $name,
                'status'      => WhatsappInstance::STATUS_PENDING,
                'webhook_url' => $webhookUrl,
                // instance_token auto-generated by model boot()
            ]);

            // Allocate credits if requested
            if ($creditsToAssign > 0) {
                $this->creditService->allocateToInstance($instance, $creditsToAssign);
            }

            return $instance->fresh();
        });
    }

    /**
     * Update an existing instance's name, webhook, or credit allocation.
     */
    public function update(
        WhatsappInstance $instance,
        array            $data,
        ?User            $actor = null,
    ): WhatsappInstance {
        return DB::transaction(function () use ($instance, $data, $actor) {
            $fillable = [];

            if (isset($data['name'])) {
                $fillable['name'] = $data['name'];
            }

            if (isset($data['webhook_url'])) {
                $fillable['webhook_url'] = $data['webhook_url'];
            }

            if (!empty($fillable)) {
                $instance->update($fillable);
            }

            // Handle additional credit allocation
            if (!empty($data['add_credits']) && $data['add_credits'] > 0) {
                $this->creditService->allocateToInstance(
                    $instance,
                    (int) $data['add_credits'],
                    $actor?->id,
                );
            }

            return $instance->fresh();
        });
    }

    /**
     * Soft-delete an instance.
     * Returns unused credits to the owner's wallet before deletion.
     *
     * @throws ValidationException
     */
    public function delete(WhatsappInstance $instance, ?User $actor = null): void
    {
        if ($instance->status === WhatsappInstance::STATUS_ACTIVE) {
            throw ValidationException::withMessages([
                'instance' => 'Cannot delete an active instance. Disconnect it first.',
            ]);
        }

        DB::transaction(function () use ($instance, $actor) {
            // Return unused credits
            $this->creditService->deallocateFromInstance($instance, $actor?->id);

            $instance->delete();
        });
    }

    /**
     * Resolve owner_type string and client_id from the owner model.
     */
    private function resolveOwnerMeta(User|Client $owner): array
    {
        if ($owner instanceof Client) {
            return [WhatsappInstance::OWNER_TYPE_CLIENT, $owner->id];
        }

        $ownerType = $owner->isSuperAdmin()
            ? WhatsappInstance::OWNER_TYPE_SUPER_ADMIN
            : WhatsappInstance::OWNER_TYPE_USER;

        return [$ownerType, $owner->client_id];
    }

    /**
     * Check that this user hasn't exceeded their client's instance limit.
     */
    private function assertInstanceLimit(User $user, ?int $clientId): void
    {
        $client = $user->client;

        if (!$client) {
            return; // No client configured, no limit
        }

        $current = WhatsappInstance::ownedBy($user->id, 'user')
            ->whereNull('deleted_at')
            ->count();

        if ($current >= $client->max_instances_per_user) {
            throw ValidationException::withMessages([
                'instance' => "Maximum instances per user reached ({$client->max_instances_per_user}). Purchase more instance credits or contact your administrator.",
            ]);
        }
    }
}